name: Deploy Medical Chatbot to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            echo "Starting Deployment..."

            cd /home/ubuntu

            # Clone repo first time only
            if [ ! -d "Build-a-Complete-Medical-Chatbot-with-LLMs-LangChain-Pinecone-Flask-AWS" ]; then
              git clone https://github.com/Vikasghandge/Build-a-Complete-Medical-Chatbot-with-LLMs-LangChain-Pinecone-Flask-AWS.git
            fi

            # Go inside project
            cd Build-a-Complete-Medical-Chatbot-with-LLMs-LangChain-Pinecone-Flask-AWS

            # Fix Git Dubious Ownership
            git config --global --add safe.directory /home/ubuntu/Build-a-Complete-Medical-Chatbot-with-LLMs-LangChain-Pinecone-Flask-AWS

            # Pull latest code
            git pull origin main

            # Stop old container
            sudo docker stop medicalbot-container || true

            # Remove old container
            sudo docker rm medicalbot-container || true

            # Remove old image
            sudo docker rmi medicalbot || true

            # Build new image
            sudo docker build -t medicalbot .

            # Run container
            sudo docker run -d \
              --name medicalbot-container \
              -p 8080:8080 \
              --env-file .env \
              medicalbot

            echo "Deployment Successful 🚀"
